-- Database: stake-with-us
-- DROP DATABASE "stake-with-us";
CREATE DATABASE "stake-with-us"
WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
CONNECTION LIMIT = -1;


-- Table: public.validator
-- DROP TABLE public.validator;
CREATE TABLE public.validator
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255) COLLATE pg_catalog."default",
    voting_power character varying(17) COLLATE pg_catalog."default",
    proposer_priority character varying(19) COLLATE pg_catalog."default",
    CONSTRAINT validator_pkey PRIMARY KEY (id),
    CONSTRAINT validator_id_address_key UNIQUE (id, address)

)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.validator
    OWNER to postgres;


-- Table: public.pub_key
-- DROP TABLE public.pub_key;
CREATE TABLE public.pub_key
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type character varying(255) COLLATE pg_catalog."default",
    value character varying(255) COLLATE pg_catalog."default",
    validator_id bigint,
    CONSTRAINT pub_key_pkey PRIMARY KEY (id),
    CONSTRAINT pub_key_value_id_validator_id_key UNIQUE (value, id, validator_id)
,
    CONSTRAINT pub_key_validator_id_fkey FOREIGN KEY (validator_id)
        REFERENCES public.validator (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.pub_key
    OWNER to postgres;
